---
- name: "Update apt cache"
  apt:
    update_cache: yes
    cache_valid_time: 86400
  retries: 10
  delay: 3

- name: "install deps"
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - "{{ cj_jenkins_deps }}"

- name: "Add Jenkins apt Key"
  apt_key:
    url: "{{ cj_repo_key_url }}"
    state: present
  become: true

- name: "Add Jenkins apt repo"
  apt_repository:
    repo: "{{ cj_repo_url }}"
    state: present
    update_cache: yes
  become: true

- name: "Download specific Jenkins version"
  get_url:
    url: "{{ cj_repo_base_url_fixed_ver }}/jenkins_{{ cj_version }}_all.deb"
    dest: "{{ cj_download_dir }}/jenkins_{{ cj_version }}_all.deb"
    validate_certs: no
    force: no
  register: cj_fixed_version
  when: cj_version is defined

- name: "Check the version of Jenkins"
  stat:
    path: "{{ cj_download_dir }}/jenkins_{{ cj_version }}_all.deb"
  register: cj_stat_version
  when: cj_version is defined

- name: "Install our specific version of Jenkins"
  apt:
    deb: "{{ cj_stat_version.stat.path }}"
    state: installed
  when: cj_version is defined and cj_stat_version.stat.exists

- name: "Jenkins [ fixed version ] package installed !?"
  apt:
    deb: "{{ cj_stat_version.stat.path }}"
    state: present
  register: cj_pkg_installed
  when: cj_version is defined and cj_stat_version.stat.exists

- name: "Jenkins [ latest version ] package installed !?"
  package:
    name: jenkins
    state: latest
  when: cj_version is undefined

- name: "Install pip requierments"
  include: "cj-pip-reqs.yml"

